<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	  <AssemblyName>CommonLibraries.Converters</AssemblyName>
	  <AssemblyTitle>CommonLibraries.Converters</AssemblyTitle>
	  <Title>Converters</Title>
	  <Version>1.0.2</Version>
	  <Copyright>Ricardo Company</Copyright>
	</PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="Converters\Tests\**" />
	  <Compile Remove="Extensions\**" />
	  <EmbeddedResource Remove="Converters\Tests\**" />
	  <EmbeddedResource Remove="Extensions\**" />
	  <None Remove="Converters\Tests\**" />
	  <None Remove="Extensions\**" />
	</ItemGroup>
	
</Project>
