<Project Sdk="Microsoft.NET.Sdk">

	<!-- NuGet package reference.-->
	<ItemGroup>
		<AssemblyName>Ricardo.CommonLibraries.Converters.Test</AssemblyName>
		<AssemblyTitle>Ricardo.CommonLibraries.Converters.Test</AssemblyTitle>
		<PackageReference Include="FluentAssertions" Version="7.2.0" />
	</ItemGroup>

	<!-- Project reference to the Converters project.-->	
	<ItemGroup>
		<ProjectReference Include="..\..\Converters.csproj" />
	</ItemGroup>
</Project>
